### ISSUE TITLE
Play sound effect when deleting item from list

### ISSUE THREAD

**Issue by thomasphillips3** [thomasphillips3/simpletodo#1]
[Play sound on button click android](http://stackoverflow.com/questions/18459122/play-sound-on-button-click-android)

**Comment by thomasphillips3** [comment]
--------- beginning of crash
09-06 19:45:45.764 10977-10977/engineering.aspire.simpletodo E/AndroidRuntime: FATAL EXCEPTION: main
                                                                               Process: engineering.aspire.simpletodo, PID: 10977
                                                                               java.lang.RuntimeException: Unable to instantiate activity ComponentInfo{engineering.aspire.simpletodo/engineering.aspire.simpletodo.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.res.Resources android.content.Context.getResources()' on a null object reference
                                                                                   at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2327)
                                                                                   at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
                                                                                   at android.app.ActivityThread.-wrap11(ActivityThread.java)
                                                                                   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
                                                                                   at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                   at android.os.Looper.loop(Looper.java:148)
                                                                                   at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                                                   at java.lang.reflect.Method.invoke(Native Method)
                                                                                   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                                   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
                                                                                Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.res.Resources android.content.Context.getResources()' on a null object reference
                                                                                   at android.content.ContextWrapper.getResources(ContextWrapper.java:87)
                                                                                   at android.view.ContextThemeWrapper.getResources(ContextThemeWrapper.java:81)
                                                                                   at android.support.v7.app.AppCompatActivity.getResources(AppCompatActivity.java:541)
                                                                                   at android.media.MediaPlayer.create(MediaPlayer.java:937)
                                                                                   at android.media.MediaPlayer.create(MediaPlayer.java:920)
                                                                                   at engineering.aspire.simpletodo.MainActivity.<init>(MainActivity.java:24)
                                                                                   at java.lang.Class.newInstance(Native Method)
                                                                                   at android.app.Instrumentation.newActivity(Instrumentation.java:1067)
                                                                                   at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2317)
                                                                                   at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476) 
                                                                                   at android.app.ActivityThread.-wrap11(ActivityThread.java) 
                                                                                   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344) 
                                                                                   at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                                   at android.os.Looper.loop(Looper.java:148) 
                                                                                   at android.app.ActivityThread.main(ActivityThread.java:5417) 
                                                                                   at java.lang.reflect.Method.invoke(Native Method) 
                                                                                   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
                                                                                   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

**Comment by thomasphillips3** [comment]
Used [this answer](http://stackoverflow.com/a/18459352/270847) to get started. Ran into the above NPE, and found [this](http://stackoverflow.com/a/25488268/270847) to help me through it.

**Comment by thomasphillips3** [comment]
https://github.com/thomasphillips3/simpletodo/pull/8
